### ISSUE TITLE
translateZ seems to not work

### ISSUE THREAD

**Issue by zachgibson** [elcontraption/flickity-transformer#9]
[I modified the basic example in CodePen](http://codepen.io/anon/pen/rjPxEo), but with the slides having no horizontal margin and I applied translateZ in the hopes zIndex would interpolate on drag. But I can't get it to work. Have you tried to do something like this?

**Comment by elcontraption** [comment]
Ha, I am literally working this out for a client project as I write this.

In your example, `translateZ` is indeed being interpolated, but the change in value from 0px to 10px is so small that it's hard to notice with the `scale` and `rotateY` functions happening at the same time.

It sounds like the effect you're looking for is a smooth change on the z-axis, with a transition between the objects as they swap stacking order. However, this is hard to accomplish because as some point the object in the background is going to have to jump in front of the object in the foreground. 

A rudimentary approach would have you setting a higher `z-index` for selected items, using Flickity's `.is-selected` class:

```css
.Slide.is-selected {
  z-index: 100;
}
```

But this won't quite do what you want, as the transition is sudden, and `.is-selected` isn't attached until the end of the drag.

Another idea, and what I'm working on for my project, is more complex. Each object in the carousel would need to have a clone set to `opacity: 0`, and the set of clones would need to be positioned at a higher level than the original objects. As the items need to transition up in the stacking order, their clone would fade in above, simulating a smooth z-index fade. As soon as the clone is at `opacity: 1`, the original item would be set to a higher z-index than its siblings, and the clone would disappear again.

If I'm able, I'll come back here with a working example, but what I have now is pretty tied up in the rest of the application code.

**Comment by elcontraption** [comment]
Closing this issue as `translateZ` is being interpolated. Feel free to continue the discussion.
